export const CHANGE_ZOOM_DOMAINS_HISTORY = 'charts/CHANGE_ZOOM_DOMAINS_HISTORY'
export const CHANGE_AIR_DOW_HOUR_CHART = 'charts/CHANGE_AIR_DOW_HOUR'
export const CHANGE_VISUAL_DOW_HOUR_CHART = 'charts/CHANGE_VISUAL_DOW_HOUR'
export const CHANGE_AIR_TYPE_HOUR_CHART = 'charts/CHANGE_AIR_TYPE_HOUR'
export const CHANGE_VISUAL_TYPE_HOUR_CHART = 'charts/CHANGE_VISUAL_TYPE_HOUR'

export const UPDATE_ANALYSIS_PERIOD = 'charts/UPDATE_ANALYSIS_PERIOD'